#pragma once

#include <SDL2/SDL.h>
#include <SDL2/SDL_image.h>
#include <SDL2/SDL_mixer.h>
#include <SDL2/SDL_ttf.h>
#include <assert.h>
#include <math.h>
#include <float.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <stdarg.h>

#include "math.h"
#include "entity_names.h"
#include "defs.h"
#include "colors.h"
#include "gfx.h"
#include "audio.h"
#include "render_batcher.h"
#include "fonts.h"
#include "render.h"
#include "personalities.h"
#include "console.h"
#include "game.h"
#include "mouse_state.h"
#include "physics.h"
#include "species.h"
#include "entities.h"
#include "decisions.h"
#include "pause_menu/pause_menu.h"
